# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/brass/all/brass.rbi
#
# brass-1.2.1

class Exception
  def assertion?; end
  def set_assertion(boolean); end
  def set_message(msg); end
end
module Kernel
  def assert(truth, *raise_arguments); end
  def fail!(*raise_arguments); end
  def refute(truth, *raise_arguments); end
  def self.assert(truth, *raise_arguments); end
  def self.fail!(*raise_arguments); end
  def self.refute(truth, *raise_arguments); end
end
