# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module Calificador::Context::TestEnvironment::EMPTY; end
module Calificador::Key::INHERITED_TRAIT; end
